# Generated by Django 3.1.14 on 2022-06-15 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0012_auto_20220615_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='previous_evolution',
            new_name='previous_evolutions',
        ),
    ]
